language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: Bionic # 18.04.x

compiler:
  - gcc



addons:
  apt:
    packages:
      - cmake
    
# blocklist
#branches:
#  except:
#    - name

#branches:
#  only:
#    - master

matrix:
  include:
    - env: CMAKE_BUILD=0 PETSC_MASTER=0 MINIMAL_BUILD=1
      os: linux
script: 
#  - ./.travis/test-qa_framework.sh
   - ./.travis/tdycore.sh
#   - ./.travis/tdycore_pflotrantest.sh

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
