language: 

before_script:
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

sudo: required

dist: Bionic # 18.04.x

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt purge python2.7-minimal
  - sudo apt-get -y install python3 python3-h5py python3-matplotlib
  - sudo apt-get -y install python3-tk python3-scipy


addons:
  apt:
    packages:
      - cmake
    
# blocklist
#branches:
#  except:
#    - name

#branches:
#  only:
#    - master

matrix:
  include:
    - env: CMAKE_BUILD=0 PETSC_MASTER=0 MINIMAL_BUILD=1
      os: linux
script: 
#  - ./.travis/test-qa_framework.sh
   - ./.travis/tdycore.sh

#after_success:
#  - bash <(curl -s https://codecov.io/bash)
